/**
 * Sam NLU — drop-in conversation + booking (does not replace desk.js).
 *
 * WIRE (Claude — do not edit this file into index.html until Sam is good;
 * do not deploy; public site stays closed):
 *
 *   <script src="./sam-voice.js"></script>
 *   <script src="./desk-nlu.js"></script>
 *   <script src="./desk.js"></script>
 *
 * desk.js changes:
 *   - Remove window.speechSynthesis / preferFemaleVoice. Never speak via TTS in-browser.
 *   - const session = SamNLU.createSession();
 *   - speak(text): said.textContent = text; addLog("sam", text); SamVoice.play(text);
 *     listen: window.addEventListener("samvoice:start", () => setMode("talk"));
 *             window.addEventListener("samvoice:end", () => setMode("idle"));
 *             window.addEventListener("samvoice:unavailable", () => {
 *               setMode("talk"); setTimeout(() => setMode("idle"), Math.min(8000, 80 * text.length));
 *             });
 *   - async handle(text) {
 *       const turn = await SamNLU.turn(session, text, { slots: remoteSlots });
 *       speak(turn.reply);
 *       if (turn.action === "show_calendar") renderCal();
 *       if (turn.action === "show_packages") showCards("Packages", SamNLU.PACKAGES);
 *       if (turn.action === "show_stages") showCards("Five stages", SamNLU.STAGES);
 *       if (turn.action === "open_book") { selected = turn.slot || selected; openBook(); }
 *       if (turn.action === "submit_book") POST turn.payload to /api/book, then speak result.
 *     }
 *   - On calendar slot click: const follow = SamNLU.selectSlot(session, slot); speak(follow.reply); openBook();
 *   - begin(): speak(SamNLU.GREETING) — exact locked line, no paraphrase.
 *   - Log prefix "Sam: " not "Desk: ". She is Sam, receptionist. Never "the desk".
 *
 * Env for /api/sam-chat and /api/tts (Vercel, never in the browser):
 *   XAI_API_KEY (preferred, grok + eve TTS) or OPENAI_API_KEY.
 *   Optional: SAM_CHAT_MODEL, SAM_TTS_VOICE=eve, OLLAMA_HOST (LAN / vercel dev only).
 */
(function (root) {
  "use strict";

  const KNOWLEDGE = root.SamKnowledge || (typeof require === "function" ? require("./sam-knowledge.js") : null);

  const GREETING =
    "Hello, welcome to Company AI Architect. I am Sam, nice to meet you, and who do I have the pleasure of helping today?";
  // SAM.md: never a personal mailbox, never a specific person. Sam takes a
  // message (SamMessages) or books; routing happens server-side.
  const CONTACT = "";

  const LINES = {
    hello: GREETING,
    hello_again: "Sam again. Discovery, prices, privacy, or I can book a free thirty minutes.",
    product:
      "We design AI automation around how your business works, from customer intake to useful job notes and connected workflows. Private AI on hardware you own is one option. What would you like to improve?",
    price:
      "Discovery is free. The written audit is one thousand five hundred. Architect plus a fourteen-day package starts at four thousand five hundred. You keep the map even if you stop after the audit.",
    privacy:
      "A private client installation can run on hardware you own. This website uses hosted services, and chat may be processed by an AI provider. Please keep customer records and sensitive information out of this conversation.",
    schedule: "Here are open discovery times in Eastern. Openings only — not who is on the book. Pick a slot.",
    schedule_none:
      "No open weekday slots in this window. Name a day and time and I'll still take the request.",
    leak: "That's the leak. I catch it before it becomes a voicemail. Pick a free thirty-minute discovery.",
    contact: "I can take a message right here and it goes straight to the right team — or I can book you a free thirty-minute discovery now.",
    human: "I take the front, and every booking goes straight to the team. Leave me a message, or pick a discovery slot and I'll file it.",
    hours: "Discovery is weekdays, nine to five Eastern, thirty minutes, free. Openings only on the calendar — no names.",
    thanks: "You're welcome. Discovery is free if you want a slot.",
    bye: "Glad to help. I'm right here whenever you need us.",
    none: "No problem. What else — prices, privacy, or a later time?",
    booked: "Your discovery booking is confirmed. I'm glad we found a time.",
    book_fail: "I couldn't confirm that booking just now. Please try again or leave a message with your preferred time.",
    need_name: "What's your name?",
    need_email: "Work email?",
    need_company: "Shop or company name?",
    need_slot: "Pick an open time on the calendar, or name a weekday and time in Eastern.",
    confirm_prompt: "I'll file that discovery now?",
  };

  const PACKAGES = [
    { t: "Discovery · Free", b: "30 minutes. Fit check. You keep the notes." },
    { t: "AI Opportunity Audit · $1,500", b: "One company, about a week. PDF, one-pager, ranked hours, 90-day plan." },
    { t: "Architect + 14-day package · $4,500+", b: "Private package on hardware you own. Ride-along on real jobs." },
  ];

  const STAGES = [
    { t: "01 Ingest", b: "How the shop actually runs." },
    { t: "02 Model", b: "Where notes live and where they leak." },
    { t: "03 Rank", b: "Hours back, effort, hardware you own." },
    { t: "04 Design", b: "Buy, integrate, or private local." },
    { t: "05 Package", b: "You keep the map and the bundle." },
  ];

  const TZ = "America/New_York";
  const LLM_MS = 8000;
  const LOCAL_MIN = 0.58;

  const WEEKDAYS = {
    sun: 0, sunday: 0,
    mon: 1, monday: 1,
    tue: 2, tues: 2, tuesday: 2,
    wed: 3, wednesday: 3,
    thu: 4, thur: 4, thurs: 4, thursday: 4,
    fri: 5, friday: 5,
    sat: 6, saturday: 6,
  };

  const HOUR_WORDS = {
    noon: 12, midnight: 0,
    one: 1, two: 2, three: 3, four: 4, five: 5, six: 6,
    seven: 7, eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12,
  };

  function createSession() {
    return {
      phase: "idle",
      greeted: false,
      booking: { name: "", email: "", company: "", pain: "", slotIso: "", slotStart: 0 },
      history: [],
      demo: null,
      businessContext: "",
      lastIntent: "",
      lastAction: "none",
    };
  }

  function normalize(text) {
    return String(text || "")
      .replace(/[“”]/g, '"')
      .replace(/[‘’]/g, "'")
      .replace(/\s+/g, " ")
      .trim();
  }

  function low(text) {
    return normalize(text).toLowerCase();
  }

  function sanitize(text) {
    let t = normalize(text);
    t = t.replace(/\bthe desk\b/gi, "the front");
    t = t.replace(/this conversation is the product\.?/gi, "");
    t = t.replace(/\bI(?:['’]m| am) the (?:desk|install)\b/gi, "I am Sam, the receptionist");
    t = t.replace(/\bthe install\b/gi, "the fourteen-day package");
    t = t.replace(/\bDesk:\s*/g, "Sam: ");
    t = t.replace(/\s{2,}/g, " ").trim();
    if (t.length > 650) t = t.slice(0, 647) + "…";
    return t;
  }

  function extractEmail(text) {
    const m = String(text || "").match(/[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}/i);
    return m ? m[0] : "";
  }

  function extractName(text, phase) {
    const t = normalize(text);
    const labeled = t.match(
      /\b(?:i(?:['’]m| am)|my name is|this is|name(?:['’]s| is)?)\s+([A-Za-z][A-Za-z'’.\-]+(?:\s+[A-Za-z][A-Za-z'’.\-]+){0,2})/i
    );
    if (labeled) {
      const n = labeled[1].replace(/\s+(from|at|with|and)\b.*$/i, "").trim();
      if (n && !/@/.test(n) && !/^(hi|hello|yes|no|ok|okay|a|an|the|interested|looking|trying|calling|ready|not|here|curious|a plumber)(?:\s|$)/i.test(n)) return n;
    }
    if (phase === "awaiting_name") {
      const stripped = t.replace(extractEmail(t), "").replace(/[,.].*$/, "").trim();
      if (
        stripped &&
        stripped.length < 60 &&
        !/@/.test(stripped) &&
        !/\b(book|schedule|price|cost|email|company|shop)\b/i.test(stripped) &&
        /^[A-Za-z][A-Za-z'’.\-]+(?:\s+[A-Za-z][A-Za-z'’.\-]+){0,3}$/.test(stripped)
      ) {
        return stripped;
      }
    }
    return "";
  }

  function looksLikeTimeish(s) {
    const t = String(s || "").toLowerCase().trim();
    if (!t) return true;
    if (/^\d{1,2}(:|\.)?[0-5]\d?\s*(a\.?m\.?|p\.?m\.?)?$/.test(t)) return true;
    if (/^\d{1,2}\s*(a\.?m\.?|p\.?m\.?)$/.test(t)) return true;
    if (/^(noon|midnight|morning|afternoon|evening)$/.test(t)) return true;
    if (WEEKDAYS[t] != null) return true;
    return false;
  }

  function plausibleCompany(raw) {
    if (!raw) return "";
    let c = String(raw)
      .replace(/\s+(and my|my email|email|at\s+\S+@).*$/i, "")
      .replace(/[.,;]+$/, "")
      .trim();
    if (!c || /@/.test(c) || looksLikeTimeish(c)) return "";
    if (/^(yes|no|ok|okay|skip|hi|hello|book|call)$/i.test(c)) return "";
    return c;
  }

  function extractCompany(text, phase) {
    const t = normalize(text);
    const from = t.match(/\bfrom\s+([A-Za-z0-9][A-Za-z0-9&.'’\- ]{1,60}?)(?=,|\.|$|\s+my\s|\s+email\b)/i);
    const labeled = t.match(/\b(?:company|shop)(?:['’]s| is)\s+([A-Za-z0-9][A-Za-z0-9&.'’\- ]{1,60})/i);
    const withCo = t.match(/\bwith\s+([A-Za-z][A-Za-z0-9&.'’\- ]{1,60}?)(?=,|\.|$)/i);
    for (const m of [from, labeled, withCo]) {
      const c = m ? plausibleCompany(m[1]) : "";
      if (c) return c;
    }
    if (phase === "awaiting_company") {
      const stripped = t.replace(extractEmail(t), "").trim();
      const c = plausibleCompany(stripped);
      if (c && c.length < 80) return c;
    }
    return "";
  }

  function extractPain(text, phase) {
    const t = normalize(text);
    const labeled = t.match(/\b(?:pain|problem|issue|leaking|missed calls)[:\s]+(.{8,180})/i);
    if (labeled) return labeled[1].trim();
    if (phase === "awaiting_pain" && t.length >= 4 && !/^(yes|no|skip|none|n\/a)$/i.test(t)) return t;
    if (phase === "awaiting_pain" && /^(skip|none|n\/a|nope)$/i.test(t)) return "";
    return "";
  }

  function parseClock(s) {
    const t = low(s);
    let ampm = null;
    if (/\b(a\.?m\.?|morning)\b/.test(t)) ampm = "am";
    if (/\b(p\.?m\.?|afternoon|evening|night)\b/.test(t)) ampm = "pm";
    let h = null;
    let min = 0;
    const hm = t.match(/\b([01]?\d|2[0-3])(?::|\.)([0-5]\d)\b/);
    if (hm) {
      h = Number(hm[1]);
      min = Number(hm[2]);
    } else {
      const hw = t.match(/\b(noon|midnight|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\b/);
      const hd = t.match(/\b([01]?\d|2[0-3])\b/);
      if (hw) h = HOUR_WORDS[hw[1]];
      else if (hd && /\b(o'?clock|a\.?m\.?|p\.?m\.?)\b/.test(t)) h = Number(hd[1]);
      else if (hd && ampm) h = Number(hd[1]);
      const mw = t.match(/\b(\d{1,2})\s*(?::|thirty|fifteen|forty[- ]?five|00)\b/);
      if (/\bthirty\b/.test(t)) min = 30;
      if (/\bfifteen\b/.test(t)) min = 15;
      if (/\bforty[- ]?five\b/.test(t)) min = 45;
      if (mw && mw[1] && Number(mw[1]) <= 59 && t.indexOf(":") >= 0) min = Number(mw[1]);
    }
    if (h == null) return null;
    if (ampm === "am") {
      if (h === 12) h = 0;
    } else if (ampm === "pm") {
      if (h < 12) h += 12;
    }
    if (h === 12 && ampm !== "am" && /\bnoon\b/.test(t)) h = 12;
    return { h, min };
  }

  function wantedWeekday(s) {
    const t = low(s);
    if (/\btomorrow\b/.test(t)) {
      const d = new Date();
      d.setDate(d.getDate() + 1);
      return d.getDay();
    }
    if (/\btoday\b/.test(t)) return new Date().getDay();
    for (const [k, v] of Object.entries(WEEKDAYS)) {
      if (new RegExp("\\b" + k + "\\b").test(t)) return v;
    }
    return null;
  }

  function dayKey(ts) {
    return new Intl.DateTimeFormat("en-CA", { timeZone: TZ }).format(new Date(ts));
  }

  function fmtDay(ts) {
    return new Intl.DateTimeFormat("en-US", {
      weekday: "short",
      month: "short",
      day: "numeric",
      timeZone: TZ,
    }).format(new Date(ts));
  }

  function fmtTime(ts) {
    return new Intl.DateTimeFormat("en-US", {
      hour: "numeric",
      minute: "2-digit",
      timeZone: TZ,
    }).format(new Date(ts));
  }

  function fmtSlot(slot) {
    if (!slot || !slot.start) return "a time we confirm";
    return fmtDay(slot.start) + " at " + fmtTime(slot.start);
  }

  function nyParts(ts) {
    const parts = new Intl.DateTimeFormat("en-US", {
      timeZone: TZ,
      weekday: "short",
      hour: "numeric",
      minute: "2-digit",
      hourCycle: "h23",
    }).formatToParts(new Date(ts));
    const get = (t) => (parts.find((p) => p.type === t) || {}).value;
    const wd = { Sun: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6 }[get("weekday")];
    return { wd, h: Number(get("hour")), min: Number(get("minute")) };
  }

  function matchSlot(text, slots) {
    const list = Array.isArray(slots) ? slots : [];
    if (!list.length) return null;
    const t = low(text);
    const clock = parseClock(t);
    const wd = wantedWeekday(t);
    if (clock == null && wd == null) return null;
    let best = null;
    let bestDelta = 1e15;
    for (const s of list) {
      const p = nyParts(s.start);
      if (wd != null && p.wd !== wd) continue;
      if (clock != null) {
        if (p.h !== clock.h) continue;
        if (clock.min != null && p.min !== clock.min && !(clock.min === 0 && p.min === 0)) {
          if (Math.abs(p.min - clock.min) > 5) continue;
        }
      }
      const delta = s.start - Date.now();
      if (delta >= 0 && delta < bestDelta) {
        best = s;
        bestDelta = delta;
      }
    }
    if (best) return best;
    if (wd != null && clock == null) {
      return list.find((s) => nyParts(s.start).wd === wd) || null;
    }
    return null;
  }

  function addScore(scores, intent, n) {
    scores[intent] = (scores[intent] || 0) + n;
  }

  function classify(text, session) {
    const s = low(text);
    const scores = {};
    const phase = (session && session.phase) || "idle";

    if (/^(hi|hello|hey|howdy|good (morning|afternoon|evening)|yo)\b/.test(s) || /^(hi|hello|hey)[.!?]*$/.test(s)) {
      addScore(scores, "greet", /^(hi|hello|hey|howdy|yo)[.!?]*$/.test(s) ? 5 : 1);
    }
    if (/\bwho are you\b|\byour name\b|\bare you sam\b|\breceptionist\b|\bwhat(?:'s| is) this\b/.test(s)) {
      addScore(scores, "who", 5);
    }
    if (/\b(what do you (do|sell|offer)|how (does it|do you) work|capabilit|product|demo|pipeline|local ai|private ai|hardware (we|you|i) own|not (a )?chatgpt|tower or mini|is this (just |only )?(chatgpt|gpt|a chatbot))\b/.test(s)) {
      addScore(scores, "product", 5);
    }
    if (/\bchatgpt\b/.test(s) && !/\bprivacy|hipaa|pii|data\b/.test(s)) addScore(scores, "product", 4);
    if (/\b(price|pricing|cost|how much|package|packages|audit|fee|rate|\$|1500|1,500|4500|4,500|thousand five|four thousand)\b/.test(s)) {
      addScore(scores, "price", 6);
    }
    if (/\b(privacy|hipaa|pii|on[- ]prem|onprem|who sees|customer (files|data)|leave the building|chatgpt login)\b/.test(s)) {
      addScore(scores, "privacy", 6);
    }
    if (/\b(book|schedule|scheduling|calendar|available|availability|slot|consult|discovery|appointment|set up a (call|time)|thirty minutes|30 minutes|free call)\b/.test(s)) {
      addScore(scores, "book", 6);
    }
    if (/\b(email|phone|contact|reach you|write you)\b/.test(s)) {
      addScore(scores, "contact", 5);
    }
    if (/\b(talk to (a )?(person|human|someone)|real person|the owner)\b/.test(s)) {
      addScore(scores, "human", 6);
    }
    if (/\b(hvac|plumb|dispatch|voicemail|front desk|after[- ]hours|missed calls?|job notes|techs?|the shop)\b/.test(s) &&
        /\b(leak|miss|voicemail|dispatch|after|notes|calls?)\b/.test(s)) {
      addScore(scores, "shop_leak", 6);
    }
    if (/\bleak(?:ing)? hours\b/.test(s)) addScore(scores, "shop_leak", 5);
    if (/\b((office |your |business )?hours|when are you open|timezone|eastern)\b/.test(s) && !/\bleak/.test(s)) {
      addScore(scores, "hours", 5);
    }
    if (/^(thanks|thank you|thx|appreciate it)[.!?]*$/.test(s) || /\bthank(s| you)\b/.test(s)) {
      addScore(scores, "thanks", 4);
    }
    if (/^(bye|goodbye|later|that'?s all|i'?m good)[.!?]*$/.test(s)) addScore(scores, "bye", 5);
    if (/^(yes|yeah|yep|yup|sure|ok|okay|please|do it|book it|that works|go ahead|confirm)[.!?]*$/.test(s)) {
      addScore(scores, "confirm", 5);
    }
    if (/^(no|nope|not now|cancel|never ?mind|stop)[.!?]*$/.test(s)) addScore(scores, "deny", 5);

    const isDemo = KNOWLEDGE && KNOWLEDGE.wantsDemo(s);
    const capabilityQuestion = /\b(?:can|could|would|how do|how would|are you able)\b/.test(s) && /\b(?:calls?|phone|messages?|appointments?|scheduling|booking|receptionist)\b/.test(s) && !(KNOWLEDGE && KNOWLEDGE.wantsBooking(s));
    if (isDemo) return { intent: "demo", confidence: 1, scores: { demo: 10 }, close: false };
    if (capabilityQuestion) return { intent: "product", confidence: 1, scores: { product: 10 }, close: false };

    const email = extractEmail(text);
    if (email) addScore(scores, "provide_contact", 4);
    if (parseClock(s) || wantedWeekday(s) != null) addScore(scores, "slot_pick", 4);

    if (phase === "awaiting_name" && !email) addScore(scores, "provide_contact", 3);
    if (phase === "awaiting_email") addScore(scores, "provide_contact", 3);
    if (phase === "awaiting_company" && !/\b(price|privacy|who)\b/.test(s)) addScore(scores, "provide_contact", 3);
    if (phase === "awaiting_slot") addScore(scores, "slot_pick", 2);
    if (phase === "awaiting_pain") addScore(scores, "provide_contact", 2);
    if (phase === "confirming") addScore(scores, "confirm", 1);

    let best = "unknown";
    let bestN = 0;
    let second = 0;
    for (const [k, v] of Object.entries(scores)) {
      if (v > bestN) {
        second = bestN;
        bestN = v;
        best = k;
      } else if (v > second) second = v;
    }
    const confidence = bestN <= 0 ? 0 : Math.min(1, bestN / (bestN + second + 3));
    const intent = bestN >= 2 ? best : "unknown";
    return { intent, confidence, scores, close: bestN - second < 2 && second > 0 };
  }

  function missingFields(session) {
    const b = session.booking;
    const miss = [];
    if (!b.slotIso) miss.push("slot");
    if (!b.name) miss.push("name");
    if (!b.email) miss.push("email");
    if (!b.company) miss.push("company");
    return miss;
  }

  function applyExtract(session, extract) {
    if (!extract) return;
    const b = session.booking;
    if (extract.name && !b.name) b.name = String(extract.name).trim();
    if (extract.email && !b.email) b.email = String(extract.email).trim();
    if (extract.company && !b.company) b.company = String(extract.company).trim();
    if (extract.pain && !b.pain) b.pain = String(extract.pain).trim();
    if (extract.slotIso && !b.slotIso) {
      b.slotIso = String(extract.slotIso);
      b.slotStart = extract.slotStart || Date.parse(extract.slotIso) || 0;
    }
  }

  function extractAll(text, session, slots) {
    const phase = session.phase;
    const out = {
      name: extractName(text, phase),
      email: extractEmail(text),
      company: extractCompany(text, phase),
      pain: extractPain(text, phase),
      slotIso: "",
      slotStart: 0,
    };
    const slot = matchSlot(text, slots);
    if (slot) {
      out.slotIso = slot.iso;
      out.slotStart = slot.start;
    }
    return out;
  }

  function bookPayload(session) {
    const b = session.booking;
    return {
      name: b.name,
      email: b.email,
      company: b.company,
      pain: b.pain || "",
      slotIso: b.slotIso,
    };
  }

  function readyToBook(session) {
    const b = session.booking;
    return !!(
      b.name &&
      b.email &&
      b.email.includes("@") &&
      b.company &&
      !looksLikeTimeish(b.company) &&
      b.slotIso
    );
  }

  function askNext(session) {
    const miss = missingFields(session);
    if (!miss.length) {
      session.phase = "confirming";
      const when = fmtSlot({ start: session.booking.slotStart, iso: session.booking.slotIso });
      return {
        reply: "That's " + when + " Eastern for " + session.booking.name + " at " + session.booking.company + ". I'll file it now?",
        action: "open_book",
      };
    }
    const next = miss[0];
    session.phase = "awaiting_" + next;
    if (next === "slot") return { reply: LINES.need_slot, action: "show_calendar" };
    if (next === "name") return { reply: LINES.need_name, action: session.booking.slotIso ? "open_book" : "none" };
    if (next === "email") return { reply: LINES.need_email, action: "open_book" };
    return { reply: LINES.need_company, action: "open_book" };
  }

  function openingsLine(slots) {
    const list = (slots || []).slice(0, 3);
    if (!list.length) return "";
    return " Next openings: " + list.map((s) => fmtSlot(s)).join("; ") + ".";
  }

  function localReply(session, intent, slots, availabilityStatus) {
    switch (intent) {
      case "greet":
        return {
          reply: session.greeted ? LINES.hello_again : GREETING,
          action: "none",
        };
      case "who":
        return {
          reply: "I'm Sam, Company AI Architect's AI receptionist. I can explain our services, demonstrate a customer conversation, help you schedule discovery, or take a message.",
          action: "none",
        };
      case "product":
        return { reply: LINES.product, action: "show_stages" };
      case "price":
        return { reply: LINES.price, action: "show_packages" };
      case "privacy":
        return { reply: LINES.privacy, action: "none" };
      case "contact":
        return { reply: LINES.contact, action: "none" };
      case "human":
        return { reply: LINES.human, action: "show_calendar" };
      case "hours":
        return { reply: LINES.hours, action: "none" };
      case "shop_leak":
        return { reply: LINES.leak, action: "none" };
      case "thanks":
        return { reply: LINES.thanks, action: "none" };
      case "bye":
        return { reply: LINES.bye, action: "none" };
      case "book":
        return {
          reply: availabilityStatus === "loading"
            ? "I’m checking the latest discovery times for you. Choose a time once the calendar appears."
            : availabilityStatus === "error"
              ? "I can’t check availability right now. You can retry the calendar or leave a message with your preferred time."
              : (slots && slots.length ? LINES.schedule : LINES.schedule_none) + openingsLine(slots),
          action: "show_calendar",
        };
      default:
        return { reply: LINES.none, action: "none" };
    }
  }

  function shouldCallLlm(guess, session, text) {
    // The rules own transactional accuracy; the model owns normal dialogue.
    // This keeps booking deterministic while letting even familiar questions
    // sound contextual instead of replaying the same canned paragraph.
    if (["book", "slot_pick", "provide_contact", "confirm", "deny"].includes(guess.intent)) return false;
    return true;
  }

  async function askLlm(session, text, guess, slots, externalSignal) {
    const ctrl = typeof AbortController !== "undefined" ? new AbortController() : null;
    const abortFromOutside = function () { if (ctrl) ctrl.abort(); };
    if (externalSignal) {
      if (externalSignal.aborted) abortFromOutside();
      else externalSignal.addEventListener("abort", abortFromOutside, { once: true });
    }
    const timer = setTimeout(() => {
      if (ctrl) ctrl.abort();
    }, LLM_MS);
    try {
      const r = await fetch("/api/sam-chat", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          message: text,
          history: session.history.slice(-8),
          phase: session.phase,
          businessContext: session.businessContext,
          demo: session.demo,
          booking: session.booking,
          guess: { intent: guess.intent, confidence: guess.confidence },
          slotHints: (slots || []).slice(0, 8).map((s) => ({ iso: s.iso, label: fmtSlot(s) })),
        }),
        signal: ctrl ? ctrl.signal : undefined,
      });
      const data = await r.json().catch(() => ({}));
      if (!r.ok || !data || data.ok === false) return null;
      return data;
    } catch (_e) {
      return null;
    } finally {
      clearTimeout(timer);
      if (externalSignal) externalSignal.removeEventListener("abort", abortFromOutside);
    }
  }

  function result(session, intent, reply, action, extra) {
    const out = Object.assign(
      {
        intent: intent,
        reply: sanitize(reply),
        action: action || "none",
        source: "rules",
        phase: session.phase,
        booking: Object.assign({}, session.booking),
        missing: missingFields(session),
        payload: null,
        slot: session.booking.slotIso
          ? { iso: session.booking.slotIso, start: session.booking.slotStart }
          : null,
        packages: PACKAGES,
        stages: STAGES,
      },
      extra || {}
    );
    session.lastIntent = intent;
    session.lastAction = out.action;
    if (out.action === "submit_book") out.payload = bookPayload(session);
    return out;
  }

  function ingest(session, userText, extract) {
    applyExtract(session, extract);
    session.history.push({ role: "user", text: normalize(userText) });
    if (session.history.length > 16) session.history.splice(0, session.history.length - 16);
  }

  function remember(session, reply) {
    session.history.push({ role: "sam", text: reply });
    session.greeted = true;
  }

  async function turn(session, userText, opts) {
    const text = normalize(userText);
    if (!session) session = createSession();
    const slots = (opts && opts.slots) || [];
    const availabilityStatus = opts && opts.slotsStatus;
    if (!text) {
      return result(session, "none", session.greeted ? LINES.none : GREETING, "none");
    }

    if (/\b(?:i|we) (?:own|run|operate|manage|work|have)|my (?:business|company|office|practice)|(?:our|my) (?:crm|software|team)/i.test(text)) session.businessContext = (session.businessContext + " " + text).trim().slice(-800);
    const guess = classify(text, session);
    const explicitBooking = !!(KNOWLEDGE && KNOWLEDGE.wantsBooking(text));
    if (explicitBooking) { guess.intent = "book"; session.demo = null; }
    const grounded = KNOWLEDGE ? KNOWLEDGE.answer(text, session) : null;
    if (grounded && grounded.intent !== "book" && (["demo", "price", "privacy"].includes(grounded.intent) || Object.prototype.hasOwnProperty.call(grounded, "demo"))) {
      if (Object.prototype.hasOwnProperty.call(grounded, "demo")) session.demo = grounded.demo;
      if (grounded.intent === "demo" || grounded.leaveBooking) session.phase = "idle";
      ingest(session, text, {});
      remember(session, grounded.reply);
      return result(session, grounded.intent, grounded.reply, grounded.action, { source: grounded.source, demo: session.demo });
    }
    // Only transactional turns can select a real time or fill a pending field.
    // A business description or a question is not consent to start booking.
    const question = /\?|^(?:can|could|would|how|what|where|why|do|does|is|are)\b/i.test(text);
    if (grounded && question && !KNOWLEDGE.wantsBooking(text)) {
      ingest(session, text, {});
      remember(session, grounded.reply);
      return result(session, grounded.intent, grounded.reply, grounded.action, { source: grounded.source });
    }
    const transactional = (!question && ["book", "slot_pick", "provide_contact", "confirm"].includes(guess.intent)) || !!(KNOWLEDGE && KNOWLEDGE.wantsBooking(text));
    const extract = extractAll(text, transactional ? session : { phase: "idle" }, transactional ? slots : []);
    ingest(session, text, extract);

    if (extract.slotIso) {
      session.booking.slotIso = extract.slotIso;
      session.booking.slotStart = extract.slotStart;
    }

    let intent = guess.intent;
    let source = "rules";
    let llm = null;

    if (intent === "greet" && !session.greeted) {
      remember(session, GREETING);
      return result(session, "greet", GREETING, "none", { source: "locked" });
    }

    const filled = !!(extract.name || extract.email || extract.company || extract.slotIso);
    if (
      filled &&
      (intent === "book" ||
        intent === "slot_pick" ||
        intent === "provide_contact" ||
        intent === "confirm")
    ) {
      if (readyToBook(session)) {
        session.phase = "confirming";
        const when = fmtSlot({ start: session.booking.slotStart });
        const reply =
          "That's " +
          when +
          " Eastern for " +
          session.booking.name +
          " at " +
          session.booking.company +
          ". I'll file it now?";
        remember(session, reply);
        return result(session, "book", reply, "open_book", { source: "rules" });
      }
      const nxt = askNext(session);
      remember(session, nxt.reply);
      return result(session, "book", nxt.reply, nxt.action, { source: "rules" });
    }

    const collecting = session.phase.indexOf("awaiting_") === 0 || session.phase === "confirming";
    if (collecting && (intent === "provide_contact" || intent === "slot_pick" || intent === "confirm" || intent === "deny" || intent === "unknown")) {
      if (intent === "deny") {
        session.phase = "idle";
        const reply = "No problem. Discovery stays free whenever you want it.";
        remember(session, reply);
        return result(session, "deny", reply, "none", { source: "rules" });
      }
      if (readyToBook(session) && (intent === "confirm" || (extract.email && extract.name && session.booking.slotIso))) {
        session.phase = "confirming";
        const when = fmtSlot({ start: session.booking.slotStart });
        const reply =
          intent === "confirm"
            ? LINES.booked
            : "That's " + when + " Eastern. I'll file it now?";
        if (intent === "confirm" || (opts && opts.autoBook)) {
          session.phase = "submitting";
          remember(session, "I'll submit your discovery request now.");
          return result(session, "book", "I'll submit your discovery request now.", "submit_book", { source: "rules" });
        }
        remember(session, reply);
        return result(session, "book", reply, "open_book", { source: "rules" });
      }
      if (intent === "confirm" && session.phase === "confirming" && readyToBook(session)) {
        session.phase = "submitting";
        remember(session, "I'll submit your discovery request now.");
        return result(session, "book", "I'll submit your discovery request now.", "submit_book", { source: "rules" });
      }
      const nxt = askNext(session);
      remember(session, nxt.reply);
      return result(session, "book", nxt.reply, nxt.action, { source: "rules" });
    }

    if (intent === "slot_pick" && extract.slotIso) {
      const nxt = askNext(session);
      remember(session, nxt.reply);
      return result(session, "book", nxt.reply, nxt.action, { source: "rules" });
    }

    if (intent === "slot_pick" && !extract.slotIso && (wantedWeekday(text) != null || parseClock(text))) {
      const reply = "I don't have that opening." + (openingsLine(slots) || " Name another weekday and time.");
      session.phase = "awaiting_slot";
      remember(session, reply);
      return result(session, "book", reply, "show_calendar", { source: "rules" });
    }

    if (intent === "confirm" && (session.lastIntent === "book" || session.lastAction === "show_calendar")) {
      session.phase = "awaiting_slot";
      const built = localReply(session, "book", slots, availabilityStatus);
      remember(session, built.reply);
      return result(session, "book", built.reply, built.action, { source: "rules" });
    }

    if (intent === "deny") {
      session.phase = "idle";
      remember(session, "Of course. We can leave that for now. What else would you like to explore?");
      return result(session, "deny", "Of course. We can leave that for now. What else would you like to explore?", "none");
    }

    if (explicitBooking) {
      const next = session.booking.slotIso ? askNext(session) : localReply(session, "book", slots, availabilityStatus);
      if (!session.booking.slotIso) session.phase = "awaiting_slot";
      remember(session, next.reply);
      return result(session, "book", next.reply, next.action, { source: "rules" });
    }

    if (shouldCallLlm(guess, session, text) && !(opts && opts.offline)) {
      llm = await askLlm(session, text, guess, slots, opts && opts.signal);
      if (llm && (llm.reply || llm.intent)) {
        source = llm.source || "llm";
        if (llm.intent && llm.intent !== "unknown") intent = llm.intent;
        const modelExtract = Object.assign({}, llm.extract || {});
        const suppliedSlot = slots.find(s => s.iso === modelExtract.slotIso);
        if (!suppliedSlot || !transactional) delete modelExtract.slotIso;
        else modelExtract.slotStart = suppliedSlot.start;
        applyExtract(session, modelExtract);
        let action = llm.action || "none";
        let reply = sanitize(llm.reply || "");
        if (!reply) {
          const built = localReply(session, intent, slots, availabilityStatus);
          reply = built.reply;
          action = built.action;
          source = "rules";
        }
        if (intent === "book" && !transactional) intent = "product";
        if (!transactional && ["show_calendar", "open_book", "need_fields"].includes(action)) action = "none";
        if (intent === "book" && action === "none") action = "show_calendar";
        if (intent === "price" && action === "none") action = "show_packages";
        if (intent === "product" && action === "none") action = "show_stages";
        if (intent === "book" && !session.booking.slotIso) session.phase = "awaiting_slot";
        if (readyToBook(session) && (intent === "book" || intent === "confirm")) {
          session.phase = "confirming";
          remember(session, reply || LINES.confirm_prompt);
          return result(session, "book", reply || LINES.confirm_prompt, "open_book", { source: source });
        }
        remember(session, reply);
        return result(session, intent, reply, action, { source: source });
      }
    }

    if (intent === "unknown" || intent === "provide_contact") intent = "none";
    const built = (!transactional && grounded) || localReply(session, intent === "none" ? "none" : intent, slots, availabilityStatus);
    if (grounded && !transactional) { intent = grounded.intent; source = grounded.source; }
    if (intent === "book") {
      session.phase = "awaiting_slot";
    }
    remember(session, built.reply);
    return result(session, intent, built.reply, built.action, { source: source });
  }

  function selectSlot(session, slot) {
    if (!session) session = createSession();
    if (!slot || !slot.iso) {
      return result(session, "book", LINES.need_slot, "show_calendar");
    }
    session.booking.slotIso = slot.iso;
    session.booking.slotStart = slot.start || Date.parse(slot.iso) || 0;
    const nxt = askNext(session);
    remember(session, nxt.reply);
    return result(session, "book", nxt.reply, nxt.action || "open_book", { source: "rules" });
  }

  function greetingTurn(session) {
    if (!session) session = createSession();
    session.greeted = true;
    remember(session, GREETING);
    return result(session, "greet", GREETING, "none", { source: "locked" });
  }

  async function submitBook(session) {
    const payload = bookPayload(session);
    let r;
    try { r = await fetch("/api/book", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    }); } catch (_e) {
      session.phase = "confirming";
      return result(session, "book", LINES.book_fail, "open_book", { error: "network_error" });
    }
    const data = await r.json().catch(() => ({}));
    if (!r.ok || !data.ok) {
      session.phase = "confirming";
      return result(session, "book", LINES.book_fail, "open_book", { source: "rules", error: data.error || "book_failed" });
    }
    const confirmed = data.status === "confirmed";
    session.phase = confirmed ? "booked" : "requested";
    const line = confirmed ? "Your booking is confirmed." : "Your appointment request was saved and still needs confirmation.";
    remember(session, line);
    return result(session, "book", line, "booked", { source: "rules", id: data.id, status: data.status });
  }

  const api = {
    GREETING: GREETING,
    CONTACT: CONTACT,
    LINES: LINES,
    PACKAGES: PACKAGES,
    STAGES: STAGES,
    createSession: createSession,
    classify: classify,
    turn: turn,
    selectSlot: selectSlot,
    greetingTurn: greetingTurn,
    submitBook: submitBook,
    applyExtract: applyExtract,
    missingFields: missingFields,
    bookPayload: bookPayload,
    sanitize: sanitize,
    fmtSlot: fmtSlot,
    fmtDay: fmtDay,
    fmtTime: fmtTime,
  };

  root.SamNLU = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof window !== "undefined" ? window : typeof globalThis !== "undefined" ? globalThis : this);
